# Generated by Django 3.0.7 on 2020-07-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_arti_datee'),
    ]

    operations = [
        migrations.AddField(
            model_name='arti',
            name='server',
            field=models.CharField(default='server', max_length=50),
        ),
    ]
