# Generated by Django 3.0.7 on 2020-07-08 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0004_arti_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arti',
            name='cUser',
            field=models.ForeignKey(default='server', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
