# Generated by Django 3.0.7 on 2020-07-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200708_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='arti',
            name='somefile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
