# Generated by Django 3.0.7 on 2020-07-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_arti_somefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arti',
            name='somefile',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
